GITHUB_CLIENT_ID:
GITHUB_CLIENT_SECRET:
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}